kr20:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: base__link01
    pid: {p: 20000.0, i: 0, d: 9000.0}
  joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: link01__link02
    pid: {p: 18000.0, i: 0, d: 8000.0}
  joint3_position_controller:
    type: position_controllers/JointPositionController
    joint: link02__link03
    pid: {p: 15000.0, i: 0, d: 7000.0}
  joint4_position_controller:
    type: position_controllers/JointPositionController
    joint: link03__link04
    pid: {p: 12000.0, i: 0, d: 7000.0}
  joint5_position_controller:
    type: position_controllers/JointPositionController
    joint: link04__link05
    pid: {p: 10000.0, i: 0, d: 5000.0}
  joint6_position_controller:
    type: position_controllers/JointPositionController
    joint: link05__link06
    pid: {p: 10000.0, i: 0, d: 5000.0}
  joint7_position_controller:
    type: position_controllers/JointPositionController
    joint: link06__gripper
    pid: {p: 10000.0, i: 0, d: 5000.0}
  gripper_left_position_controller:
    type: position_controllers/JointPositionController
    joint: gripper__gripper_left
    pid: {p: 1000.0, i: 0, d: 50.0}
  gripper_right_position_controller:
    type: position_controllers/JointPositionController
    joint: gripper__gripper_right
    pid: {p: 1000.0, i: 0, d: 50.0}
